# Generated by Django 3.0.4 on 2020-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20200401_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_evaluated',
        ),
        migrations.AddField(
            model_name='profilevitals',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
