# Generated by Django 3.0.4 on 2020-04-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200402_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(default=-1)),
                ('spo2', models.FloatField(default=-1)),
                ('breathing_rate', models.FloatField(default=-1)),
                ('blood_pressure', models.CharField(default=None, max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.CharField(default=None, max_length=255)),
                ('comments', models.CharField(default=None, max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
